#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Use OpenFOAM 4.x
export PATH=/usr/lib64/openmpi/bin/:/usr/lib64/ccache:/usr/local/bin:/bin:/usr/local/sbin:/usr/sbin:/home/fweiler/.local/bin:/home/fweiler/bin && export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib/ && source /home/fweiler/OpenFOAM/OpenFOAM-4.x/etc/bashrc

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm log.* 
rm -r proc*
runApplication foamCleanPolyMesh
runApplication cartesianMesh
runApplication topoSet -dict system/createCut.topoSetDict
runApplication subsetMesh oversetBox -patch overset -overwrite

runApplication mergeMeshes . ../backgroundMesh -overwrite

rm log.topoSet

runApplication topoSet -dict system/createOverset.topoSetDict

restore0Dir

runApplication setFields
#------------------------------------------------------------------------------
